version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    cooldown:
      default-days: 7
    ignore:
      - dependency-name: css-loader
        versions:
          - 5.0.1
          - 5.0.2
          - 5.1.0
          - 5.1.1
          - 5.1.2
          - 5.1.3
          - 5.2.0
          - 5.2.1
          - 5.2.2
      - dependency-name: "@babel/core"
        versions:
          - 7.13.10
          - 7.13.13
          - 7.13.14
          - 7.13.15
      - dependency-name: "@babel/plugin-transform-async-to-generator"
        versions:
          - 7.12.1
          - 7.12.13
          - 7.13.0
      - dependency-name: whatwg-fetch
        versions:
          - 3.5.0
          - 3.6.1
      - dependency-name: "@babel/plugin-proposal-class-properties"
        versions:
          - 7.12.1
          - 7.12.13
      - dependency-name: "@babel/plugin-transform-arrow-functions"
        versions:
          - 7.12.1
          - 7.12.13
      - dependency-name: eslint-plugin-react
        versions:
          - 7.22.0
      - dependency-name: eslint-plugin-import
        versions:
          - 2.22.1
