[project]
name = 'baselayer_template_app'
version = "0.0.0"
requires-python = "==3.14.*"
dependencies = [
  "baselayer"
]

[tool.uv]
package = false
workspace = { members = ["baselayer"] }

[tool.uv.sources]
baselayer = { workspace = true }
